# Generated by Django 5.1.1 on 2025-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookgenre_name_alter_readergenre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
