# Generated by Django 5.1.1 on 2025-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='readergenre',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
