# Generated by Django 5.1.1 on 2025-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_readergenre_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='blogs',
            field=models.ManyToManyField(related_name='authors', through='api.AuthorBlog', to='api.blog'),
        ),
    ]
