# Generated by Django 5.1.1 on 2025-02-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_siteuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(default='blank', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(related_name='friends_with+', through='api.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
