# Generated by Django 5.1.1 on 2025-03-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blog_post_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reader',
            new_name='user',
        ),
    ]
