# Generated by Django 5.1.1 on 2025-02-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_genre_book_genres_review_book_reviews_userbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
    ]
