# Generated by Django 5.1.1 on 2025-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='reader',
            name='goal_five',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='reader',
            name='goal_four',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='reader',
            name='goal_one',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reader',
            name='goal_three',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='reader',
            name='goal_two',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
