# Generated by Django 5.1.1 on 2025-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_authorbook_cover_image_reader_goal_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='token_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='two_factor_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
