# Generated by Django 5.1.1 on 2025-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('READING', 'Reading'), ('START', 'Not started')], default='START', max_length=10),
        ),
    ]
