# Generated by Django 5.1.1 on 2025-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
