# Generated by Django 5.1.1 on 2025-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_review_title_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('READING', 'Reading'), ('WISHLIST', 'Wishlist')], default='START', max_length=10),
        ),
    ]
