# Generated by Django 5.1.1 on 2025-03-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userbook_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='username',
            new_name='friendUsername',
        ),
        migrations.AddField(
            model_name='friendship',
            name='userUsername',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
