# Generated by Django 5.1.1 on 2025-03-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_username_friendship_friendusername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUsername', models.CharField(default='username', max_length=100)),
                ('friendUsername', models.CharField(default='username', max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='messages',
            field=models.ManyToManyField(related_name='messages_with+', through='api.Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
