# Generated by Django 4.2.11 on 2025-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message_siteuser_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
    ]
