# Generated by Django 4.2.11 on 2025-03-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_siteuser_book_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='message',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='book_count',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user_books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
