# Generated by Django 4.2.11 on 2025-03-24 11:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_book_reviews_remove_friendship_friend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('siteuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('book_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
            },
            bases=('api.siteuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
