# Generated by Django 4.2.11 on 2025-03-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('blurb', models.TextField(max_length=2000)),
                ('isbn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('READING', 'Reading'), ('WISHLIST', 'Wishlist')], default='START', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
                ('rating', models.IntegerField(choices=[(0, '0 Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('message', models.TextField(max_length=2000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUsername', models.CharField(default='username', max_length=100)),
                ('friendUsername', models.CharField(default='username', max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to='api.reader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to='api.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUsername', models.CharField(default='username', max_length=100)),
                ('friendUsername', models.CharField(default='username', max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='api.reader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='api.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(through='api.Review', to='api.reader'),
        ),
        migrations.AddField(
            model_name='reader',
            name='friends',
            field=models.ManyToManyField(related_name='friends_with+', through='api.Friendship', to='api.reader'),
        ),
        migrations.AddField(
            model_name='reader',
            name='messages',
            field=models.ManyToManyField(related_name='messages_with+', through='api.Message', to='api.reader'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user_books',
            field=models.ManyToManyField(through='api.UserBook', to='api.book'),
        ),
    ]
