# Generated by Django 4.2.11 on 2025-03-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
