# Generated by Django 4.2.11 on 2025-03-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_author_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
